"""Phase 3 — error-analysis report for the drop-type classifier.

Dumps every test-set disagreement of the best binary model vs the LLM
label, buckets them heuristically, and emits a self-contained markdown
report with a hand-review section and a shadow-deployment recommendation.

Usage: ./venv/bin/python -m scripts.ml.error_report
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List

import joblib
import numpy as np
import pandas as pd

from scripts.ml.features import assemble, dataset_sha256, load_or_build_embeddings

REPORT = Path("docs/proposals/REPORT_drop_type_classifier_v1.md")


def bucket(row: pd.Series, cluster_dates: set) -> str:
    days = row["days_since_earnings"]
    if pd.notna(days) and abs(int(days)) <= 5:
        return "earnings-adjacent"
    if row["decision_date"] in cluster_dates:
        return "sector-day cluster"
    if len(str(row["news_context"])) < 500:
        return "thin news"
    return "other"


def fmt_table(headers: List[str], rows: List[List[str]]) -> List[str]:
    return (["| " + " | ".join(headers) + " |",
             "|" + "---|" * len(headers)]
            + ["| " + " | ".join(str(c) for c in r) + " |" for r in rows])


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dataset", default="data/ml/drop_type_dataset.parquet")
    parser.add_argument("--model", default="models/drop_type_clf_v1.joblib")
    parser.add_argument("--cache", default="data/ml/embeddings.npz")
    args = parser.parse_args()

    art = joblib.load(args.model)
    df = pd.read_parquet(args.dataset).reset_index(drop=True)
    sha = dataset_sha256(Path(args.dataset))
    assert art["dataset_sha256"] == sha, "model was trained on a different dataset"

    text_cols = ["news_context", "c1_news", "c1_competitive",
                 "c1_market_sentiment", "c1_technical"]
    embs = load_or_build_embeddings(df, text_cols, Path(args.cache), sha)
    binary = art["binary"]
    X = assemble(df, binary["tier"], embs)
    is_test = (df["split"] == "test").to_numpy()
    cal = binary["calibrated"]
    p_true = cal.predict_proba(X[is_test])[:, list(cal.classes_).index(True)]
    fire = p_true >= art["threshold"]

    test = df[is_test].reset_index(drop=True)
    test["p_fire"] = np.round(p_true, 3)
    test["model_fire"] = fire
    test["disagree"] = test["model_fire"] != test["gate_trigger"]
    cluster_dates = set(
        test["decision_date"].value_counts()[lambda s: s >= 3].index
    )
    dis = test[test["disagree"]].copy()
    dis["bucket"] = (
        dis.apply(bucket, axis=1, cluster_dates=cluster_dates)
        if len(dis) else pd.Series(dtype=str)
    )

    baselines = json.loads(Path("data/ml/results_baselines.json").read_text())
    clf_res = json.loads(Path("data/ml/results_classifier.json").read_text())
    bar = clf_res["success_bar"]

    lines: List[str] = [
        "# Drop-Type Classifier v1 — Error Analysis (Phase 3)",
        "",
        f"Generated by `scripts/ml/error_report.py`. Dataset sha256 `{sha[:16]}…`,",
        f"encoder `{clf_res['encoder']}`, best binary model: tier "
        f"{binary['tier']}, head {binary['head_name']}, fire threshold "
        f"{art['threshold']} (below → no-fire).",
        "",
        "The LLM label is the *teacher*, not ground truth — a disagreement is",
        "an audit artifact. Hand review decides: model wrong / label wrong /",
        "ambiguous.",
        "",
        "## Metrics summary (fixed time-split test)",
        "",
    ]
    rows = []
    for name, r in baselines["baselines"].items():
        rows.append([name, r["seven_class"]["macro_f1"], r["binary"]["f1"],
                     r["binary"]["precision"], r["binary"]["recall"]])
    for tname in ("seven_class", "binary"):
        for run in clf_res["runs"]:
            if run["target"] == tname:
                label = f"bge-small tier {run['tier']} + {run['head']}"
                if tname == "seven_class":
                    rows.append([label, run["test_metric"], "", "", ""])
                else:
                    rows.append([label, "", run["test_metric"],
                                 run["precision"], run["recall"]])
    lines += fmt_table(
        ["model", "7c macro-F1", "bin F1", "bin P", "bin R"], rows)
    lines += [
        "",
        f"**Success bar** (binary F1 ≥ {bar['bar']} and > earnings-window "
        f"heuristic {bar['heuristic_f1']}): model {bar['binary_f1']} — "
        f"**{'MET' if bar['met'] else 'NOT MET'}**.",
        "",
        f"Note: the success-bar number ({bar['binary_f1']}) is the raw "
        f"uncalibrated head's F1. The disagreements below use the shipped "
        f"decision rule — calibrated probabilities with fire threshold "
        f"{art['threshold']} — whose test F1 is "
        f"{clf_res['best_binary']['test_metric_with_abstention']}. The two "
        "rules differ substantially because calibration + thresholding "
        "makes the model fire far less often.",
        "",
        "## Batch-drift slice (test agreement per label_month)",
        "",
    ]
    lines += fmt_table(
        ["label_month", "agreement"],
        [[m, a] for m, a in clf_res["agreement_by_label_month"].items()])
    lines += [
        "",
        f"## Disagreements ({len(dis)} of {len(test)} test rows)",
        "",
        "Bucket counts: " + ", ".join(
            f"{b}: {n}" for b, n in dis["bucket"].value_counts().items()),
        "",
    ]
    for b in dis["bucket"].unique():
        lines += [f"### Bucket: {b}", ""]
        for _, r in dis[dis["bucket"] == b].iterrows():
            snippet = " ".join(str(r["c1_news"])[:300].split())
            lines += [
                f"- **{r['symbol']} {r['decision_date']}** — LLM: "
                f"`{r['drop_type']}` (gate_trigger={r['gate_trigger']}), "
                f"model: {'FIRE' if r['model_fire'] else 'NO-FIRE'} "
                f"(p={r['p_fire']})",
                f"  > {snippet}",
                "",
            ]
    lines += ["## Hand review", "",
              "Verdict per disagreement (fill in):", ""]
    for _, r in dis.iterrows():
        lines.append(
            f"- [ ] {r['symbol']} {r['decision_date']} — verdict: "
            "model wrong / label wrong / ambiguous")
    drift = list(clf_res["agreement_by_label_month"].values())
    drift_spread = round(max(drift) - min(drift), 4) if len(drift) > 1 else 0.0
    stable = clf_res["best_binary"]["seed_sd"] <= 0.03
    if bar["met"] and stable and drift_spread <= 0.10:
        rec = ("**Recommendation: ship to shadow.** The binary model clears the "
               "0.85 bar, beats the heuristic, is seed-stable and shows no "
               "sharp per-month drift. Next step is Phase 4 shadow deployment "
               "(out of scope for this run).")
    elif bar["binary_f1"] > bar["heuristic_f1"]:
        rec = ("**Recommendation: iterate.** The model beats the heuristic but "
               f"misses the full bar (F1 {bar['binary_f1']} vs {bar['bar']}, "
               f"seed sd {clf_res['best_binary']['seed_sd']} (trivially 0 for "
               "the deterministic LogReg head — the check was designed for "
               f"LightGBM, which did not run), month drift "
               f"spread {drift_spread}). Review the hand-review verdicts first "
               "— label noise may cap the ceiling.")
        rec += (
            " Caveat: the earnings-window heuristic is degenerate in the "
            "test window (earnings metadata nearly absent), so beating it "
            "is a low bar — on the raw-head comparison the model also "
            "trails the majority baseline and TF-IDF. Judge the iterate "
            "round against those, not the heuristic."
        )
    else:
        rec = ("**Recommendation: dataset too noisy / model not better than "
               "the heuristic.** Do not ship. Hand-review the disagreements to "
               "decide whether labels or features are the bottleneck.")
        rec += (
            " Caveat: the earnings-window heuristic is degenerate in the "
            "test window (earnings metadata nearly absent), so beating it "
            "is a low bar — on the raw-head comparison the model also "
            "trails the majority baseline and TF-IDF. Judge the iterate "
            "round against those, not the heuristic."
        )
    lines += ["", "## Recommendation", "", rec, ""]

    REPORT.write_text("\n".join(lines))
    print(f"wrote {REPORT} ({len(dis)} disagreements)")


if __name__ == "__main__":
    main()
