import sys
import os
from dotenv import load_dotenv

# Add project root to path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

# Load env vars
load_dotenv()

from app.services.email_service import email_service

def test_real_email():
    print("Testing real email sending...")
    print(f"SMTP Server: {email_service.smtp_server}")
    print(f"Sender: {email_service.sender_email}")
    print(f"Recipient: {email_service.recipient_email}")
    
    if not email_service.sender_email or "your_sender_email" in email_service.sender_email:
        print("ERROR: Credentials not configured in .env yet.")
        return

    try:
        email_service.send_notification(
            symbol="TEST-STOCK", 
            percentage=-10.5, 
            price=123.45,
            research_report="This is a test report generated by the verification script."
        )
        print("Test email function called. Check your inbox!")
    except Exception as e:
        print(f"Failed to send test email: {e}")

if __name__ == "__main__":
    test_real_email()
